<?php
${"GLOBALS"}["vrxougoybf"]="vrxougoybf";
${"GLOBALS"}["gysbjjimrf"]="merah";
${"GLOBALS"}["owmuxayhuu"]="owmuxayhuu";
${"GLOBALS"}["bcopkjwvtu"]="kuning";
${"GLOBALS"}["aguevskrpm"]="aguevskrpm";
${"GLOBALS"}["zlkquvqlgv"]="magentha";
${"GLOBALS"}["fguethpcpu"]="cyan";
${"GLOBALS"}["byllbbpofp"]="byllbbpofp";
${"GLOBALS"}["zyurkfwhum"]="zyurkfwhum";
${"GLOBALS"}["qnoazrslla"]="qnoazrslla";	//10
${"GLOBALS"}["pacrgmeqgb"]="lhijau";
${"GLOBALS"}["rfpojqprvg"]="lkuning";
${"GLOBALS"}["bghewauyrg"]="lbiru";
${"GLOBALS"}["gveaqpamwu"]="lmagentha";
${"GLOBALS"}["dodsuxvmsw"]="lcyan";	//15
${"GLOBALS"}["mawnudqhcq"]="putih";
${"GLOBALS"}["gcaluyzkyx"]="\n \n";
${"GLOBALS"}["lfiugwnoov"]="\n";
${${"GLOBALS"}["vrxougoybf"]}	="[1;30m";
${${"GLOBALS"}["gysbjjimrf"]}	="[1;31m";
${${"GLOBALS"}["owmuxayhuu"]}	="[1;32m";
${${"GLOBALS"}["bcopkjwvtu"]}	="[1;33m";
${${"GLOBALS"}["aguevskrpm"]}	="[1;34m";
${${"GLOBALS"}["zlkquvqlgv"]}	="[1;35m";
${${"GLOBALS"}["fguethpcpu"]}	="[1;36m";
${${"GLOBALS"}["byllbbpofp"]}	="[1;37m";
${${"GLOBALS"}["zyurkfwhum"]}	="[1;39m";
${${"GLOBALS"}["qnoazrslla"]}	="[1;91m";
${${"GLOBALS"}["pacrgmeqgb"]}	="[1;92m";
${${"GLOBALS"}["rfpojqprvg"]}	="[1;93m";
${${"GLOBALS"}["bghewauyrg"]}	="[1;94m";
${${"GLOBALS"}["gveaqpamwu"]}	="[1;95m";
${${"GLOBALS"}["dodsuxvmsw"]}	="[1;96m";
${${"GLOBALS"}["mawnudqhcq"]}	="[1;97m";
${${"GLOBALS"}["gcaluyzkyx"]}	="\n \n";
${${"GLOBALS"}["lfiugwnoov"]}	="\n";
${"GLOBALS"}["rylbptxvod"]	="config";
${"GLOBALS"}["srqfxpxblt"]	="i";	//20
${"GLOBALS"}["nkjjasgksm"]	="acc";
${"GLOBALS"}["dvgyccjvnx"]	="load";
${"GLOBALS"}["mndbdhbibr"] 	= "0";
${"GLOBALS"}["wsyyombcdu"] 	= "0";
${${"GLOBALS"}["mndbdhbibr"]} = 0;	
${${"GLOBALS"}["wsyyombcdu"]} = 0;
${"GLOBALS"}["ycveydlsrm"]	="curl_init";	//25
${"GLOBALS"}["clcujshirq"]	="result";
${"GLOBALS"}["powyxxpset"]	="info";
${"GLOBALS"}["wamdeydsqu"]	="content";
${"GLOBALS"}["gzhahywehz"]	="js";	
${"GLOBALS"}["dkbffteehl"]	="code";//30
${"GLOBALS"}["midskhwems"]	="msg";
${"GLOBALS"}["utgtdqixik"]	="data";
${"GLOBALS"}["urxubrkmoq"]	="nickname";
${"GLOBALS"}["mbeylilxfz"]	="gold_flag"; 
${"GLOBALS"}["vrdgkzjaso"]	="invitation_code";//35
${"GLOBALS"}["ywpsdvazmn"]	="balance";
${"GLOBALS"}["gkwyzdkykd"]	="total_balance";
${"GLOBALS"}["ugiysjplpr"]	="friend_num";
${"GLOBALS"}["lvjlprtdij"]	="apprentice_status";	
${"GLOBALS"}["aduibwfmrt"]	="level";	//40
${"GLOBALS"}["cywvuyyjkr"]	="level_per";
${"GLOBALS"}["wwmdquyldb"]	="curl_init";
${"GLOBALS"}["cxmiyfguoh"]	="result";
${"GLOBALS"}["xeqcmaskgw"]	="info";	
${"GLOBALS"}["ifqqbxrjjy"]	="content";	//45
${"GLOBALS"}["rjicuqmlqn"]	="js";
${"GLOBALS"}["gmsxcmtcwp"]	="code";
${"GLOBALS"}["kqygujqkbf"]	="msg";
${"GLOBALS"}["dakevtsdku"]	="data";	
${"GLOBALS"}["bvwxafosoj"]	="curl_init";	//50
${"GLOBALS"}["imeiuqzxda"]	="result";
${"GLOBALS"}["ttoalzcfow"]	="info";
${"GLOBALS"}["ihxrkpqvjr"]	="content";
${"GLOBALS"}["xcaapyfdfh"]	="js";	
${"GLOBALS"}["dnvzeutegq"]	="code";	//55
${"GLOBALS"}["assxwslqfb"]	="msg";
${"GLOBALS"}["uexbzpncbw"]	="data";
${"GLOBALS"}["zflwnovskc"]	="gold_flag";
${"GLOBALS"}["stpplqccyt"]	="gold_tomorrow";
${"GLOBALS"}["dvssnofnem"]	="curl_init";	//60
${"GLOBALS"}["ejuatajeuf"]	="result";	
${"GLOBALS"}["lzqtgaachf"]	="info";
${"GLOBALS"}["yvazptcocb"]	="content";
${"GLOBALS"}["uynvpslyyi"]	="js";
${"GLOBALS"}["dduzoteyil"]	="code";	//65	
${"GLOBALS"}["wawltegdbh"]	="msg";	
${"GLOBALS"}["rzddzxuzxg"]	="data";
${"GLOBALS"}["idthzfshui"]	="gold_tribute";
${"GLOBALS"}["sgmeikzzcw"]	="update_time"; 
${"GLOBALS"}["kzraernfyl"]	="is";	//70
${"GLOBALS"}["ihsqrltzmy"]	="time_difference";
${"GLOBALS"}["bvghvlpppp"]	="curl_init";
${"GLOBALS"}["mldolzuxxu"]	="result";
${"GLOBALS"}["wqrzqfajbt"]	="info";	
${"GLOBALS"}["kthbaipfsp"]	="content";	//75	
${"GLOBALS"}["ztxuhmmtrg"]	="js";
${"GLOBALS"}["fnhrvtohem"]	="code";
${"GLOBALS"}["lfjisdfwea"]	="msg";
${"GLOBALS"}["odmtmiburz"]	="data";
${"GLOBALS"}["xmmpqubdzy"]	="gold_flag";	//80	
${"GLOBALS"}["pdpmojzzca"]	="count";	
${"GLOBALS"}["npmdppwwfw"]	="isUpdate";
${"GLOBALS"}["rfxynhipka"]	="userLevel";
${"GLOBALS"}["qkcvsfwiiw"]	= "1.5";
${${"GLOBALS"}["qkcvsfwiiw"]}	= 14;
${"GLOBALS"}["grhjifwpmf"]	= "dl";
${${"GLOBALS"}["grhjifwpmf"]}	= "Bot sedang dalam perbaikan. Mungkin akan membutuhkan waktu beberapa Jam. ^-^";
?>
